<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net4.8</TargetFramework>
    <ImplicitUsings>true</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <OutputType>exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UseSharedCompilation>false</UseSharedCompilation>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UnlimitedSharp.Analyzer\UnlimitedSharp.Analyzer.csproj" OutputItemType="Analyzer" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Delegates.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Delegates.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Delegates.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Delegates.tt</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
